routes/web.php
<?php

use App\Http\Controllers\Backend\Contact\ContactController;
use App\Http\Controllers\Backend\Organization\OrganizationController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

//Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('organizations', OrganizationController::class);

Route::get('/contacts/{token}/email-verification', [ContactController::class, 'emailVerification'])->name('contacts.email-verification');
Route::get('/contacts/check-email-is-unique/{email}/{id}', [ContactController::class, 'checkEmailIsUnique']);
Route::resource('contacts', ContactController::class);

app/Models/Contact/Contact.php
<?php

namespace App\Models\Contact;

use App\Models\Contact\Traits\ContactRelationship;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class Contact extends Model
{
    use HasFactory,
        ContactRelationship,
        Notifiable;


    protected $guarded = [];

    protected $dates = ['birth_date', 'email_verified_at'];
}

app/Models/Contact/Traits/ContactRelationship.php
<?php

namespace App\Models\Contact\Traits;

use App\Models\ContactMobile\ContactMobile;
use App\Models\Organization\Organization;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

trait ContactRelationship
{
    public function organization(): BelongsTo
    {
        return $this->belongsTo(Organization::class);
    }

    public function mobiles()
    {
        return $this->hasMany(ContactMobile::class, 'contact_id');
    }
}

app/Http/Controllers/Api/ContactController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\ContactsCollection;
use App\Repositories\Api\ContactRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class ContactController extends Controller
{
    /**
     * @var ContactRepository
     */
    private $contactRepository;

    public function __construct(ContactRepository $contactRepository)
    {
        $this->contactRepository = $contactRepository;
    }

    public function index(Request $request)
    {
        $contacts = new ContactsCollection($this->contactRepository->getPaginated($request->all()));

        return response()->json($contacts, 200);
    }

    public function getFilteredWithOrganization(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'organization_id' => 'required|exists:organizations,id'
        ]);

        if($validator->fails()){
            return response()->json($validator->errors(), 422);
        }

        $contacts = new ContactsCollection($this->contactRepository->getFilteredWithOrganization($request->all()));

        return response()->json($contacts, 200);
    }

    public function getFilteredWithEmail(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'email' => 'required|email'
        ]);

        if($validator->fails()){
            return response()->json($validator->errors(), 422);
        }

        $contacts = new ContactsCollection($this->contactRepository->getFilteredWithEmail($request->all()));

        return response()->json($contacts, 200);
    }
}

app/Http/Controllers/Backend/Contact/ContactController.php
<?php

namespace App\Http\Controllers\Backend\Contact;

use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\Contact\StoreContactRequest;
use App\Http\Requests\Backend\Contact\UpdateContactRequest;
use App\Models\Contact\Contact;
use App\Models\Organization\Organization;
use App\Repositories\Backend\ContactRepository;
use Carbon\Carbon;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;

class ContactController extends Controller
{
    /**
     * @var ContactRepository
     */
    private $contactRepository;

    public function __construct(ContactRepository $contactRepository)
    {
        $this->contactRepository = $contactRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return View
     */
    public function index(Request $request)
    {
        $contacts = $this->contactRepository->getPaginated($request->all(), 10);

        return view('contacts.index', compact('contacts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $organizations = Organization::all();

        return view('contacts.create', [
            'organizations' => $organizations
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  StoreContactRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreContactRequest $request)
    {
        $contact = $this->contactRepository->store($request->all());

        return response()->json($contact, 200);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Contact\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function edit(Contact $contact)
    {
        $organizations = Organization::all();

        return view('contacts.edit', [
            'contact' => $contact->load('mobiles', 'organization'),
            'organizations' => $organizations
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Contact\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateContactRequest $request, Contact $contact)
    {
        $contact = $this->contactRepository->update($contact, $request->all());

        return response()->json($contact, 200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Contact\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function destroy(Contact $contact)
    {
        $this->contactRepository->delete($contact);

        return back()->withFlashSuccess('Contact Deleted Successfully!');
    }

    public function checkEmailIsUnique(string $email, int $id)
    {
        $contact = Contact::where('email', $email)->first();
        if(! $contact){
            return response()->json('valid', 200);
        }

        if($id !== 0){
            $contactById = Contact::find($id);
            if($contactById->email === $email){
                return response()->json('valid', 200);
            }
            else{
                return response()->json('invalid', 422);
            }
        }

        return response()->json('invalid', 422);
    }

    public function emailVerification(string $token)
    {
        $contact = Contact::where('email_verification_token', $token)->first();

        if($contact){
            $contact->email_verified_at = Carbon::now();
            $contact->email_verification_token = null;
            $contact->save();
        }

        return view('contacts.email_verified');
    }
}

resources/views/contacts/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Create Contact</div>
                    <div class="card-body">
                        <create-contact :organizations="{{ $organizations }}" />
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/contacts/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Edit Contact</div>
                    <div class="card-body">
                        <edit-contact
                            :contact="{{ $contact }}"
                            :organizations="{{ $organizations }}"
                        ></edit-contact>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/contacts/email_verified.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    Email Verified Successfully!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/contacts/filter.blade.php
<form method="get" action="{{ route('contacts.index') }}">
    @csrf
    <div class="mb-4">
        <div class="row" style="padding-top: 10px">
            <div class="col-12 col-md-12 ">
                <div class="row" style="padding-top: 10px">
{{--                    <div class="col-md-1">Search</div>--}}
                    <div class="col-md-3">
                        <input type="text" value="{{ request()->get('query') }}" name="query" class="form-control" placeholder="Search by name, email or mobile">
                    </div>

{{--                    <div class="col-md-1">Search..</div>--}}
                    <div class="col-md-3">
                        <select name="is_valid" class="form-control" id="is_valid">
                            <option value="0">Email Status</option>
                            <option value="valid" {{ request()->get('is_valid') === 'valid' ? 'selected' : '' }}>Validated</option>
                            <option value="invalid" {{ request()->get('is_valid') === 'invalid' ? 'selected' : '' }}>not validated</option>
                        </select>
                    </div>

                    <div class="filter-btns col-md-4">
                        <button type="submit" id="" class="btn btn-success btn-w-m btn-success btn-rounded">Search</button>
                        <a href="{{ route('contacts.index') }}" class="btn btn-success btn-w-m btn-danger btn-rounded">cancel</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

resources/views/contacts/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">

                <div class="mb-2 float-right">
                    <a href="{{ route('contacts.create') }}" class="btn btn-primary">Add Contact</a>
                </div>

                @include('contacts.filter')

                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th scope="col">First Name</th>
                        <th scope="col">Last Name</th>
                        <th scope="col">Organization</th>
                        <th scope="col">Email</th>
                        <th scope="col">Is Verified?</th>
                        <th scope="col">Last Updated</th>
                        <th scope="col">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($contacts as $contact)
                        <tr>
                            <td>{{ $contact->first_name }}</td>
                            <td>{{ $contact->last_name }}</td>
                            <td>{{ optional($contact->organization)->name }}</td>
                            <td>{{ $contact->email }}</td>
                            <td>{{ $contact->email_verified_at ? 'yes' : 'no' }}</td>
                            <td>{{ $contact->updated_at->diffForHumans() }}</td>
                            <td>
                                <div style="display: flex; justify-content: center; align-items: center">
                                    <a href="{{ route('contacts.edit', $contact->id) }}" class="btn btn-primary">Edit</a>
                                    <form class="ml-1" method="post" action="{{ route('contacts.destroy', $contact->id) }}">
                                        @method('delete')
                                        @csrf
                                        <button class="btn btn-danger delete-row" type="submit">Delete</button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>

                <div class="text-center">
                    @if($contacts->count() === 0)
                        <h4>No Data Found!</h4>
                    @endif
                </div>

                {{ $contacts->render() }}


            </div>
        </div>
    </div>
@endsection