routes/web.php
<?php

use App\Http\Controllers\Backend\Contact\ContactController;
use App\Http\Controllers\Backend\Organization\OrganizationController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

//Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('organizations', OrganizationController::class);

Route::get('/contacts/{token}/email-verification', [ContactController::class, 'emailVerification'])->name('contacts.email-verification');
Route::get('/contacts/check-email-is-unique/{email}/{id}', [ContactController::class, 'checkEmailIsUnique']);
Route::resource('contacts', ContactController::class);

app/Models/Organization/Organization.php
<?php

namespace App\Models\Organization;

use App\Models\Organization\Traits\OrganizationAttribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Organization extends Model
{
    use HasFactory,
        OrganizationAttribute;

    protected $guarded = [];

    protected $dates = ['licensed_date'];

    protected $appends = ['organizationLogo'];
}

app/Models/Organization/Traits/OrganizationAttribute.php
<?php

namespace App\Models\Organization\Traits;

use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;

trait OrganizationAttribute
{
    public function getOrganizationLogoAttribute()
    {
        $path = Storage::url('organizations/' . $this->logo);

        if (! Storage::exists('/organizations/' . $this->logo) || is_null($this->logo)) {
            $path = asset('assets/images/organization.svg');
        }

        return $path;
    }
}

app/Http/Controllers/Api/OrganizationController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\OrganizationResource;
use App\Http\Resources\OrganizationsCollection;
use App\Models\Organization\Organization;
use App\Repositories\Api\OrganizationRepository;
use Illuminate\Http\Request;

class OrganizationController extends Controller
{
    /**
     * @var OrganizationRepository
     */
    private $organizationRepository;

    public function __construct(OrganizationRepository $organizationRepository)
    {
        $this->organizationRepository = $organizationRepository;
    }

    public function index(Request $request)
    {
        $organizations = new OrganizationsCollection($this->organizationRepository->getPaginated($request->all()));

        return response()->json($organizations, 200);
    }
}

app/Http/Controllers/Backend/Organization/OrganizationController.php
<?php

namespace App\Http\Controllers\Backend\Organization;

use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\Organization\StoreOrganizationRequest;
use App\Http\Requests\Backend\Organization\UpdateOrganizationRequest;
use App\Models\Organization\Organization;
use App\Models\OrganizationCategory;
use App\Repositories\Backend\OrganizationRepository;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class OrganizationController extends Controller
{
    /**
     * @var OrganizationRepository
     */
    private $organizationRepository;

    public function __construct(OrganizationRepository $organizationRepository)
    {
        $this->organizationRepository = $organizationRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $organizations = $this->organizationRepository->getPaginated(10);

        return view('organizations.index', compact('organizations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create()
    {
        $categories = OrganizationCategory::pluck('name', 'name')
                        ->prepend('Select Category', '');

        return view('organizations.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreOrganizationRequest  $request
     * @return Response
     */
    public function store(StoreOrganizationRequest $request)
    {
        if ($request->hasFile('file')) {
            $request->validate([
                'file' => 'mimes:jpeg,jpg,png'
            ]);
            $request->file->store('organizations', 'public');
            $request['logo'] = $request->file->hashName();
        }

        $this->organizationRepository->store($request->except('file'));

        return back()->withFlashSuccess('Organization created successfully!');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Organization\Organization  $organization
     * @return Response
     */
    public function edit(Organization $organization)
    {
        $categories = OrganizationCategory::pluck('name', 'name')
                        ->prepend('Select Category', '');

        return view('organizations.edit', compact('categories', 'organization'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Organization\Organization  $organization
     * @return Response
     */
    public function update(UpdateOrganizationRequest $request, Organization $organization)
    {
        if ($request->hasFile('file')) {
            $request->validate([
                'file' => 'mimes:jpeg,jpg,png'
            ]);
            $request->file->store('organizations', 'public');
            $request['logo'] = $request->file->hashName();
        }

        $this->organizationRepository->update($organization, $request->except('file'));

        return redirect()->route('organizations.index')
                         ->withFlashSuccess('Organization Updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Organization\Organization  $organization
     * @return Response
     */
    public function destroy(Organization $organization)
    {
        $response = $this->organizationRepository->delete($organization);

        return back()->withFlashSuccess('Organization removed successfully!');
    }
}

resources/views/organizations/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Create Organization</div>
                <div class="card-body">
                    {!! Form::open(['route' => 'organizations.store', 'files' => true]) !!}
                    @include('organizations.form')
                    <button type="submit" class="btn btn-primary">Submit</button>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/organizations/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Create Organization</div>
                <div class="card-body">
                    {!! Form::model($organization , ['route' => [ 'organizations.update', $organization->id ], 'method' => 'patch' ,'files' => true]) !!}
                        @include('organizations.form')
                        <button type="submit" class="btn btn-primary">Update</button>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/organizations/form.blade.php
<div class="form-group">
    {!! Form::label('name', 'Name') !!}
    <span class="text-danger">*</span>
    {!! Form::text('name', null, [ 'class' => ($errors->has('name')) ? 'form-control is-invalid' : 'form-control' , 'id' => 'name', 'placeholder' => 'Organization Name']); !!}
</div>
<div class="form-group">
    {!! Form::label('category', 'Category'); !!}
    <span class="text-danger">*</span>
    {!! Form::select('category', $categories, null , ['class' => ($errors->has('category')) ? 'form-control is-invalid' : 'form-control', 'id' => 'category']); !!}
</div>
<div class="form-group">
    {!! Form::label('trade_license', 'Trade License'); !!}
    {!! Form::text('trade_license', null , ['class' => 'form-control', 'id' => 'trade_license', 'placeholder' => 'Trade License']); !!}
</div>

<div class="form-group">
    {!! Form::label('licensed_date', 'Licensed Date'); !!}
    {!! Form::date('licensed_date', isset($organization) ? $organization->licensed_date : null , ['class' => 'form-control', 'id' => 'trade_license']); !!}
</div>

@isset($organization)
    <div class="form-group">
        <img width="150px" height="150px" src="{{ $organization->organizationLogo }}" alt="{{ $organization->name }}">
    </div>
@endisset

<div class="form-group">
    {!! Form::label('file', 'Logo'); !!}
    <input type="file" name="file">
</div>

resources/views/organizations/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">

                <div class="mb-2 float-right">
                    <a href="{{ route('organizations.create') }}" class="btn btn-primary">Add Organization</a>
                </div>

                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Category</th>
                        <th scope="col">Trade License</th>
                        <th scope="col">Licensed Date</th>
                        <th scope="col">Last Updated</th>
                        <th scope="col">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($organizations as $organization)
                        <tr>
                            <td>{{ $organization->name }}</td>
                            <td>{{ $organization->category }}</td>
                            <td>{{ $organization->trade_license }}</td>
                            <td>{{ $organization->licensed_date->format('Y-m-d') }}</td>
                            <td>{{ $organization->updated_at->diffForHumans() }}</td>
                            <td>
                                <div style="display: flex; justify-content: center; align-items: center">
                                    <a href="{{ route('organizations.edit', $organization->id) }}" class="btn btn-primary">Edit</a>
                                    <form class="ml-1" method="post" action="{{ route('organizations.destroy', $organization->id) }}">
                                        @method('delete')
                                        @csrf
                                        <button class="btn btn-danger delete-row" type="submit">Delete</button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                {{ $organizations->render() }}
            </div>
        </div>
    </div>
@endsection